# NOTE: see data readme about "No Representation Without Population Act" and ADJ_ variables

# Shapefile info:
shapefile_path: 'data/md_mggg/MD_precincts_abs/MD-precincts_abs.shp'  # Path to shapefile
population_col: 'ADJ_POP'       # Column where total population is stored
vap_col: 'ADJ_VAP'              # Column where voting age population is stored
bvap_col: 'ADJ_BVAP'            # Column where black voting age population is stored
hvap_col: 'HVAP'                # Column where hispanic voting age population is stored
district_col: 'CD'              # Column where district assignment is stored
county_col: 'COUNTY'            # Column where county is stored
pad_district_numbers: False     # Pad district numbers with leading 0s

# Output info:
total_steps: 100                # Total number of accepted maps to generate
output_path: 'results_MD.csv'   # File path for output CSV
create_images: True             # Save district map images to f'{output_path.rstrip(".csv")}_images/'
image_interval: 1000            # Save every nth map to f'{output_path.rstrip(".csv")}_images/'
take_every_ends: 100            # Save every map for the first and last n maps to see direct progression

# Election info:
elections:
  'PRES12':
    dem_col: 'PRES12D'
    rep_col: 'PRES12R'
  'SEN12':
    dem_col: 'SEN12D'
    rep_col: 'SEN12R'
  'USH12':
    dem_col: 'USH12D'
    rep_col: 'USH12R'
  'GOV14':
    dem_col: 'GOV14D'
    rep_col: 'GOV14R'
  'USH14':
    dem_col: 'USH14D'
    rep_col: 'USH14R'
  'SSEN14':
    dem_col: 'SSEN14D'
    rep_col: 'SSEN14R'
  'PRES16':                     # Name of the election used for partisan metrics
    dem_col: 'PRES16D'          # Name of the column where democratic votes are stored
    rep_col: 'PRES16R'          # Name of the column where republican votes are stored
  'SEN16':
    dem_col: 'SEN16D'
    rep_col: 'SEN16R'
  'USH16':
    dem_col: 'USH16D'
    rep_col: 'USH16R'
  'GOV18':
    dem_col: 'GOV18D'
    rep_col: 'GOV18R'
  'SEN18':
    dem_col: 'SEN18D'
    rep_col: 'SEN18R'
  'USH18':
    dem_col: 'USH18D'
    rep_col: 'USH18R'
  'SSEN18':
    dem_col: 'SSEN18D'
    rep_col: 'SSEN18R'

# Districts:
total_districts: 8              # Total number of districts in the given shapefile

# Opportunity Scoring:
opportunity_threshold: 0.4      # Percent minority population to be considered "minority opportunity"
black_opp_target: 3             # Target number of black opportunity districts
black_opp_weight: 1             # The weight of black opportunity district scoring
hispanic_opp_target: 3          # Target number of hispanic opportunity districts
hispanic_opp_weight: 1          # The weight of hispanic opportunity district scoring

# County Split Scoring:
county_split_coefficient: 2     # (this)^k is the coefficient of the w_{2+k} score

# Score function weights:
population_score_weight: 1      # Weight for population score
compactness_score_weight: 1     # Weight for compactness score
county_score_weight: 1          # Weight for county split score
opportunity_score_weight: 0     # Weight for opportunity score
