# Shapefile info:
shapefile_path: 'data/nc_mggg/NC_VTD/NC_VTD.shp' # Path to shapefile
population_col: 'TOTPOP'        # Column where total population is stored
vap_col: 'VAP'                  # Column where voting age population is stored
bvap_col: 'BVAP'                # Column where black voting age population is stored
hvap_col: 'HVAP'                # Column where hispanic voting age population is stored
district_col: 'CD'              # Column where district assignment is stored
county_col: 'County'            # Column where county is stored
pad_district_numbers: False     # Pad district numbers with leading 0s

# Output info:
total_steps: 100000             # Total number of accepted maps to generate
output_path: 'results_NC.csv'   # File path for output CSV

# Election info:
elections:
  'GOV12':
    dem_col: 'EL12G_GV_D'
    rep_col: 'EL12G_GV_R'
  'SEN14':
    dem_col: 'EL14G_US_1'
    rep_col: 'EL14G_USS_'
  'PRES12':
    dem_col: 'EL12G_PR_D'
    rep_col: 'EL12G_PR_R'
  'PRES16':                     # Name of the election used for partisan metrics
    dem_col: 'EL16G_PR_D'       # Name of the column where democratic votes are stored
    rep_col: 'EL16G_PR_R'       # Name of the column where republican votes are stored
  'SEN16':
    dem_col: 'EL16G_US_1'
    rep_col: 'EL16G_USS_'
  'GOV16':
    dem_col: 'EL16G_GV_D'
    rep_col: 'EL16G_GV_R'

# Districts:
total_districts: 13             # Total number of districts in the given shapefile

# Opportunity Scoring:
opportunity_threshold: 0.4      # Percent minority population to be considered "minority opportunity"
black_opp_target: 3             # Target number of black opportunity districts
black_opp_weight: 1             # The weight of black opportunity district scoring
hispanic_opp_target: 1          # Target number of hispanic opportunity districts
hispanic_opp_weight: 1          # The weight of hispanic opportunity district scoring

# County Split Scoring:
county_split_coefficient: 10    # (this)^k is the coefficient of the w_{2+k} score

# Score function weights:
population_score_weight: 2399   # Weight for population score
compactness_score_weight: 0.1944 # Weight for compactness score
county_score_weight: 0.1019     # Weight for county split score
opportunity_score_weight: 10    # Weight for VRA score
