# Shapefile info:
shapefile_path: 'data/tx_mggg/TX_vtds/TX_vtds.shp'  # Path to shapefile
population_col: 'TOTPOP'        # Column where total population is stored
vap_col: 'VAP'                  # Column where voting age population is stored
bvap_col: 'BVAP'                # Column where black voting age population is stored
hvap_col: 'HISPVAP'             # Column where hispanic voting age population is stored
district_col: 'USCD'            # Column where district assignment is stored
county_col: 'COUNTY'            # Column where county is stored
pad_district_numbers: True      # Pad district numbers with leading 0s

# Output info:
total_steps: 100                # Total number of accepted maps to generate
output_path: 'TX_results.csv'   # File path for output CSV

# Election info:
election_name: 'PRES16'         # Name of the election used for partisan metrics
election_dem_col: 'PRES16D'     # Name of the column where democratic votes are stored
election_rep_col: 'PRES16R'     # Name of the column where republican votes are stored

# Districts:
total_districts: 36             # Total number of districts in the given shapefile

# VRA Compliance:
opportunity_threshold: 0.4      # Percent minority population to be considered "minority opportunity"
black_opp_target: 4             # Target number of black opportunity districts
black_opp_weight: 1             # The weight of black opportunity district VRA compliance
hispanic_opp_target: 14         # Target number of hispanic opportunity districts
hispanic_opp_weight: 1          # The weight of hispanic opportunity district VRA compliance

# County Split Scoring:
county_split_coefficient: 10    # (this)^k is the coefficient of the w_{2+k} score

# Score function weights:
population_score_weight: 1      # Weight for population score
compactness_score_weight: 1     # Weight for compactness score
county_score_weight: 1          # Weight for county split score
vra_score_weight: 1             # Weight for VRA score
