# Shapefile info:
shapefile_path: 'data/oh_mggg/OH_precincts/OH_precincts.shp'  # Path to shapefile
population_col: 'TOTPOP'        # Column where total population is stored
vap_col: 'VAP'                  # Column where voting age population is stored
bvap_col: 'BVAP'                # Column where black voting age population is stored
hvap_col: 'HVAP'                # Column where hispanic voting age population is stored
district_col: 'CD'              # Column where district assignment is stored
county_col: 'COUNTY'            # Column where county is stored
pad_district_numbers: True      # Pad district numbers with leading 0s
override_pop_constraint: False  # Ignore 2% population constraint (useful for analyzing new maps with old census data)

# Output info:
total_steps: 150000             # Total number of accepted maps to generate
output_path: 'results_OH.csv'   # File path for output CSV
create_images: False            # Save district map images to f'{output_path.rstrip(".csv")}_images/'
image_interval: 1000            # Save every nth map to f'{output_path.rstrip(".csv")}_images/'
take_every_ends: 100            # Save every map for the first and last n maps to see direct progression

# Election info:
elections:
  'PRES16':                     # Name of the election used for partisan metrics
    dem_col: 'PRES16D'          # Name of the column where democratic votes are stored
    rep_col: 'PRES16R'          # Name of the column where republican votes are stored
  'SEN16':
    dem_col: 'SEN16D'
    rep_col: 'SEN16R'
  'USH16':
    dem_col: 'USH16D'
    rep_col: 'USH16R'
  'SSEN16':
    dem_col: 'SSEN16D'
    rep_col: 'SSEN16R'
  'STH16':
    dem_col: 'STH16D'
    rep_col: 'STH16R'

# Districts:
total_districts: 16             # Total number of districts in the given shapefile

# Opportunity Scoring:
opportunity_threshold: 0.425    # Percent minority population to be considered "minority opportunity"
black_opp_target: 2             # Target number of black opportunity districts
black_opp_weight: 1             # The weight of black opportunity district scoring
hispanic_opp_target: 0          # Target number of hispanic opportunity districts
hispanic_opp_weight: 0          # The weight of hispanic opportunity district scoring

# County Split Scoring:
county_split_coefficient: 2     # (this)^k is the coefficient of the w_{2+k} score

# Score function weights:
population_score_weight: 2171   # Weight for population score
compactness_score_weight: 0.1165 # Weight for compactness score
county_score_weight: 0.06664    # Weight for county split score
opportunity_score_weight: 0     # Weight for opportunity score
