# Shapefile info:
shapefile_path: 'data/mn_mggg/MN16/mn_precincts16.shp'  # Path to shapefile
population_col: 'TOTPOP'        # Column where total population is stored
vap_col: 'VAP'                  # Column where voting age population is stored
bvap_col: 'BVAP'                # Column where black voting age population is stored
hvap_col: 'HVAP'                # Column where hispanic voting age population is stored
district_col: 'CONGDIST'        # Column where district assignment is stored
county_col: 'COUNTYNAME'        # Column where county is stored
pad_district_numbers: False     # Pad district numbers with leading 0s

# Output info:
total_steps: 100                # Total number of accepted maps to generate
output_path: 'results_MN.csv'   # File path for output CSV

# Election info:
elections:
  'PRES16':                     # Name of the election used for partisan metrics
    dem_col: 'PRES16D'          # Name of the column where democratic votes are stored
    rep_col: 'PRES16R'          # Name of the column where republican votes are stored
  'USH16':
    dem_col: 'USH16D'
    rep_col: 'USH16R'
  'SSEN16':
    dem_col: 'SSEN16D'
    rep_col: 'SSEN16R'
  'SH16':
    dem_col: 'SH16D'
    rep_col: 'SH16R'

# Districts:
total_districts: 8              # Total number of districts in the given shapefile

# Opportunity Scoring:
opportunity_threshold: 0.3      # Percent minority population to be considered "minority opportunity"
black_opp_target: 2             # Target number of black opportunity districts
black_opp_weight: 1             # The weight of black opportunity district scoring
hispanic_opp_target: 0          # Target number of hispanic opportunity districts
hispanic_opp_weight: 0          # The weight of hispanic opportunity district scoring

# County Split Scoring:
county_split_coefficient: 2     # (this)^k is the coefficient of the w_{2+k} score

# Score function weights:
population_score_weight: 3175   # Weight for population score
compactness_score_weight: 0.2686 # Weight for compactness score
county_score_weight: 0.10893    # Weight for county split score
opportunity_score_weight: 0     # Weight for opportunity score

# Normalize scores by dividing (J(E') - J(E)) by J(E)
normalize_scores: False
