# Shapefile info:
shapefile_path: 'data/ma_mggg/MA_precincts_12_16/MA_precincts_12_16.shp' # Path to shapefile
population_col: 'TOTPOP'        # Column where total population is stored
vap_col: 'VAP'                  # Column where voting age population is stored
bvap_col: 'BVAP'                # Column where black voting age population is stored
hvap_col: 'HVAP'                # Column where hispanic voting age population is stored
district_col: 'CD'              # Column where district assignment is stored
county_col: 'COUNTYFP10'        # Column where county is stored
pad_district_numbers: False     # Pad district numbers with leading 0s

# Output info:
total_steps: 100                # Total number of accepted maps to generate
output_path: 'results_MA.csv'   # File path for output CSV

# Election info:
elections:
  'SEN12':
    dem_col: 'SEN12D'
    rep_col: 'SEN12R'
  'PRES12':
    dem_col: 'PRES12D'
    rep_col: 'PRES12R'
  'SEN14':
    dem_col: 'SEN14D'
    rep_col: 'SEN14R'
  'PRES16':                     # Name of the election used for partisan metrics
    dem_col: 'PRES16D'          # Name of the column where democratic votes are stored
    rep_col: 'PRES16R'          # Name of the column where republican votes are stored
  'GOV14':
    dem_col: 'GOV14D'
    rep_col: 'GOV14R'
  'GOV18':
    dem_col: 'GOV18D'
    rep_col: 'GOV18R'
  'SEN18':
    dem_col: 'SEN18D'
    rep_col: 'SEN18R'

# Districts:
total_districts: 9              # Total number of districts in the given shapefile

# VRA Compliance:
opportunity_threshold: 0.4      # Percent minority population to be considered "minority opportunity"
black_opp_target: 0             # Target number of black opportunity districts
black_opp_weight: 0             # The weight of black opportunity district VRA compliance
hispanic_opp_target: 1          # Target number of hispanic opportunity districts
hispanic_opp_weight: 1          # The weight of hispanic opportunity district VRA compliance

# County Split Scoring:
county_split_coefficient: 10    # (this)^k is the coefficient of the w_{2+k} score

# Score function weights:
population_score_weight: 1      # Weight for population score
compactness_score_weight: 1     # Weight for compactness score
county_score_weight: 1          # Weight for county split score
vra_score_weight: 1             # Weight for VRA score
