---
title: "Comps Data"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r exampleData}
#basic cleaning process for csv with same form as first dataset
mn_test <- read_csv("test_MN_data.csv")

mn_work <- cbind("map" = c(1:nrow(mn_test)), mn_test)

mn_tidy <- mn_work %>% 
  pivot_longer(!c(map, efficiency_gap, mean_median, seats_won),
                         names_to = c(".value", "district"),
                         names_sep = -1) 
colnames(mn_tidy) <- colnames(mn_tidy) %>% str_replace_all("_", "")
```

```{r readfcn_exampleData}
#function to clean data structed same as sample data
read_clean <- function(url){
  data <- read_csv(url)
  data1 <- cbind("map" = c(1:nrow(data)), data)
  data_tidy <- data1 %>% 
  pivot_longer(!c(map, efficiency_gap, mean_median, seats_won),
                         names_to = c(".value", "district"),
                         names_sep = -1) 
  colnames(data_tidy) <- colnames(data_tidy) %>% str_replace_all("_", "")
  return(data_tidy)
}
```  

```{r}
read.csv("MN_data2.csv")
```



```{r data_1_distributions}
mn <- read_csv("MN_data.csv")
nrow(mn)

efficiency_dist <- ggplot(mn) +
  geom_histogram(aes(efficiency_gap)) +
  labs(title = "Minnesota Ensemble Distribution of Efficiency Gap", x="Efficiency Gap", subtitle = "For 2000 states without an acceptance function")
efficiency_dist

efficiency_density <- ggplot(mn) +
  geom_density(aes(efficiency_gap)) +
  labs(title = "Minnesota Ensemble Density Distribution of Efficiency Gap", x="Efficiency Gap", subtitle = "For 2000 states without an acceptance function")
efficiency_density

partisan_dist <- ggplot(mn) +
  geom_histogram(aes(partisan_bias)) +
  labs(title = "Minnesota Ensemble Distribution of Partisan Bias", x="Partisan Bias", subtitle = "For 2000 states without an acceptance function")
partisan_dist

partisan_density <- ggplot(mn) +
  geom_density(aes(partisan_bias)) +
  labs(title = "Minnesota Ensemble Density Distribution of Partisan Bias", x="Partisan Bias", subtitle = "For 2000 states without an acceptance function")
partisan_density

```

